### ISSUE TITLE
Improve the CSS to get away from Tailwind

### ISSUE THREAD

**Issue by tchoutri** [flora-pm/flora-server#102]
Currently, the CSS of the application is handled in an awkward way:

* Tailwind is used both in `class` mode and in `@apply` mode in the source files and the CSS files.
* It's not being written in the spirit of hinting the browser, and its sins are numerous.
* ~~It's not being linted as part of the CI.~~

**Comment by TixieSalander** [comment]
As discussed elsewhere, I'm planning on work on this part, replacing the job done by tailwind (having design tokens in one config file, and generate utility CSS classes) by a [PostCSS plugin](https://github.com/saneef/postcss-design-token-utils)

**Comment by TixieSalander** [comment]
I see the resolution of this in two times:
1. Replace Tailwind by PostCSS plugins but keep the HTML as it. 
2. And secondly take the time to refactor into components the areas where there is see abusive use of utility classes.

For the first step the work is done, I'm just waiting for #587 and #588 to be merged (some cleaning and tooling upgrades on the frontend side) to able to make a clean PR. 👌

**Comment by tchoutri** [comment]
fixed by #589
