### ISSUE TITLE
Background jobs management

### ISSUE THREAD

**Issue by tchoutri** [flora-pm/flora-server#110]
With the sheer amount of packages being processed, it's interesting to have some kind of background job management going on, especially for retries and such.

The [odd-jobs](https://www.haskelltutorials.com/odd-jobs) library will be used for such a task.

**Comment by jappeace** [comment]
![image](https://user-images.githubusercontent.com/3874017/172051563-89943cd5-904f-4215-afbb-7891900032e3.png)
