### ISSUE TITLE
  When flora.pm is added to the browser as a custom search engine using the prompt doesn't disappear.

### ISSUE THREAD

**Issue by Wheatwizard** [flora-pm/flora-server#198]
## Environment

* Operating System: nixOs
* Browser: Firefox 103.0.2 
* Version or commit: v1.0.0

## Expected Behaviour

When flora.pm is added to the browser as a custom search engine using the prompt to do so disappears.

## Actual Behaviour

Even once added to the browser there is still an option to add the custom search engine again, doing so yields an error as the search engine is already added.

## Instructions for reproduction

1. Add flora.pm as a custom search engine. 
![flora1](https://user-images.githubusercontent.com/15176276/189532094-72839de1-de6b-4fc2-85ab-ba052603c0e7.png)
2. Observe that the prompt persists
![flora2](https://user-images.githubusercontent.com/15176276/189532096-5ebdfffa-5e54-4818-936b-787d04154588.png)
3. Add it again, and observe an error.
![flora3](https://user-images.githubusercontent.com/15176276/189532101-7aebe638-00e6-42bf-8f7e-ce25abdcc0f4.png)

**Comment by tchoutri** [comment]
Thanks a lot for the ticket!

**Comment by tchoutri** [comment]
fixed by #427
