### ISSUE TITLE
Emails in "Maintainers" sections could be proper mailto links

### ISSUE THREAD

**Issue by tchoutri** [flora-pm/flora-server#204]
We could do a parsing pass on the "Maintainers" section metadata and turn the emails into proper `mailto://` links.

**Comment by danieled-it** [comment]
@tchoutri do you think the following regex replacement would be enough to fit your requirement?
```
<(\S+@\S+\.\w+)>
<mailto://$1>
```
Results will go from `<me@mydomain.com>` to `<mailto://me@mydomain.com>`.

From what I see it'll take action on 53 results in 32 files.
I'm asking as it'll impact also some `author:` sections, not sure if it'll be ok for you, plus I see some emails will still be missed as they're not wrapped in `<>`, a bit of manual action needed there.

**Comment by tchoutri** [comment]
We'd have to write a parser for https://www.rfc-editor.org/rfc/rfc5322#section-3.4 with megaparsec and such

**Comment by danieled-it** [comment]
Understood, I'm afraid that's out of my reach unfortunately, thanks for the clarification and sorry!

**Comment by tchoutri** [comment]
After gathering some input, I have come to the realisation that making email addresses readily available for use for crawlers and spam bots is not great. I am therefore closing this ticket as WONTDO
