### ISSUE TITLE
Packages are shown as their own dependent

### ISSUE THREAD

**Issue by tchoutri** [flora-pm/flora-server#208]
Situation: A package name is shown in its own dependents. This is confusing because we don't show that this dependency relationship is between the main library and its test suite. As such, we should prune out the package name from the list of its dependencies.

Notes for test:

The package name should not appear in the dependents of one of its releases.

Raised in https://github.com/flora-pm/flora-server/discussions/207

**Comment by larsrh** [comment]
Could be a related issue: For `bytestring`, the overview page lists 6744 dependents, whereas the detail view shows 8264 results.

**Comment by tchoutri** [comment]
fixed by #242
