### ISSUE TITLE
Namespace browsing

### ISSUE THREAD

**Issue by tchoutri** [flora-pm/flora-server#219]
We should be able to browse a namespace's packages when accessing it, via https://flora.pm/packages/@haskell (for instance).

**Comment by tchoutri** [comment]
I'm thinking of having a modifier in the search bar: `org:<package name>`. Such as 

`org:haskell vector`.

**Comment by tchoutri** [comment]
@SethLivy

**Comment by kenranunderscore** [comment]
I'd like to try my luck with this, but tentatively (not sure how well I'll grok the code base, and how much time I'll be able to find in the coming days).

**Comment by tchoutri** [comment]
closed by #375
