### ISSUE TITLE
Leading whitespace in code-blocks for package

### ISSUE THREAD

**Issue by fendor** [flora-pm/flora-server#264]
## Environment

* Operating System: Linux archlinux 6.0.2
* Toolchain (compiler + version): [FILL HERE]
* Version or commit: flora.pm (accessed 29.10.2022 15:12 CET)

## Expected Behaviour

Renders code as-is

## Actual Behaviour

Flora seems to introduce a leading whitespace character in-front of code-blocks:

![image](https://user-images.githubusercontent.com/8463814/198833621-a231b141-6840-4ff2-b114-33300cb828db.png)

![image](https://user-images.githubusercontent.com/8463814/198833707-61cb072e-98f5-443f-9a56-a2f4029ffde6.png)

Note, this whitespace seemingly does not exist on GitHub: https://raw.githubusercontent.com/Lysxia/first-class-families/master/README.md and https://hackage.haskell.org/package/first-class-families and https://github.com/Lysxia/first-class-families#readme render it properly

## Instructions for reproduction

* Go to https://flora.pm/packages/@hackage/first-class-families

**Comment by tchoutri** [comment]
That's a regression, thank you very much.
