### ISSUE TITLE
Flora website doesn't respect theme choice when navigating site

### ISSUE THREAD

**Issue by skykanin** [flora-pm/flora-server#320]
## Environment

* Operating System: NixOS x86_64-linux. Kernel v6.1.1
* Browser: Firefox 108.0 (64-bit)

## Expected Behaviour
Flora keeps my theme choice consistent across all pages on flora.

## Actual Behaviour
Flora resets the theme choice based on the `prefers-color-scheme` media query whenever you navigate to a new page.

## Instructions for reproduction
- Open <https://flora.pm> in your browser
- Switch the theme in the top right corner
- Navigate to any other page and see the theme reset

**Comment by tchoutri** [comment]
Fixed by #321
