### ISSUE TITLE
Display dependencies on specific components

### ISSUE THREAD

**Issue by tchoutri** [flora-pm/flora-server#351]
Let's take two packages, [`a`](https://github.com/flora-pm/flora-server/blob/development/test/fixtures/Cabal/a.cabal) and [`b`](https://github.com/flora-pm/flora-server/blob/development/test/fixtures/Cabal/b.cabal).

`b.cabal` has the following components:

* Main library component `b`
* `b:sublib`
* `b:anothersublib`

`a.cabal` has the following components

* Main library component
  * Depends on `b:sublib` and `b:anothersublib`
* Executable component
  * Depends on `b:sublib` and `b:anothersublib`

---

Today, the granularity of dependencies is not set at the component level but at the package level (which is implicitly the main library component).

![Screenshot 2023-03-05 at 21-34-35 @hackage_b](https://user-images.githubusercontent.com/15848443/222984475-4b1471c7-d8d2-4df1-bc70-65e17bd88f20.png)
![Screenshot 2023-03-05 at 21-34-20 @hackage_a](https://user-images.githubusercontent.com/15848443/222984476-c0aa26fd-343d-4cd5-a45c-07e847dbb40e.png)

**Comment by RaoulHC** [comment]
What you've described isn't actually possible, the sublibraries that you can specify are internal and cannot be consumed by other packages (see details [here](https://cabal.readthedocs.io/en/3.8/cabal-package.html?highlight=internal%20libraries#sublibs)).

Having said that it would be nice to specify which components within a package another components depend on. If I throw the current flora cabal description into a flora instance all the internal sublibraries get missed.
