### ISSUE TITLE
Update Docker setup to use GHC 9.4.4

### ISSUE THREAD

**Issue by kenranunderscore** [flora-pm/flora-server#368]
As mentioned in #367 the Docker setup in its current state supports GHC 9.2, but GHC 9.4.4 should be used. (It's also broken atm, as GHC 9.4.4 is already referenced.)

I'd like to at least try fixing this, but I can't promise anything time-wise :/

One proposition I have would be to maybe use a different base image, like [the official Haskell ones](https://hub.docker.com/_/haskell) that are already compatible with GHC 9.4.4 and come with `ghcup` installed. That would get rid of some of the steps in the `Dockerfile` in its current state and would also mean making the whole setup a tiny bit more reproducible, as pinning the base image now would pin "more stuff", if that makes sense. What do you think?

**Comment by tchoutri** [comment]
@gbogard what was the precise point of contention that had prevented you from using the official haskell image?

**Comment by kenranunderscore** [comment]
Ah, I see the current Dockerfile uses Ubuntu, while the Haskell ones seem to use Debian. Maybe that really makes a difference here with all the dependencies.
