### ISSUE TITLE
Breadcrumbs for the namespace > name title

### ISSUE THREAD

**Issue by tchoutri** [flora-pm/flora-server#378]
After the completion of #219, we may want to refine the UI of the title as it is now: 

![image](https://user-images.githubusercontent.com/15848443/230729260-7f49477b-a5af-43a5-ad28-b532cfa761bb.png)

Some inspirations can come from https://semantic-ui.com/collections/breadcrumb.html and https://setproduct.com/blog/breadcrumbs-ui-design#rec475058759.

cc @kenranunderscore if you're interested. :)

**Comment by tchoutri** [comment]
@TixieBorg if you have an opinion on this kind of things, feel free to chime in :+1:

**Comment by TixieBorg** [comment]
To be sure to understand: the idea would be to replace the name or add a breadcrumb to improve hierarchy's visibility? 

In any case here's some general resources about designing breadcrumbs:
- https://www.nngroup.com/articles/breadcrumbs/
- https://www.smashingmagazine.com/2009/03/breadcrumbs-in-web-design-examples-and-best-practices/

And examples of implementations:
- https://www.w3.org/WAI/ARIA/apg/patterns/breadcrumb/examples/breadcrumb/
- https://scottaohara.github.io/a11y_breadcrumbs/

**Comment by kenranunderscore** [comment]
Since you pinged me: I'm interested in principle, but this is really something I have no experience with whatsoever, so I'm probably not the right person for the "job". Also, what about Tixie's question @tchoutri: I'd imagine this would be in addition to the existing title and not a replacement?

**Comment by tchoutri** [comment]
The idea is be to replace the content of the `<h1>` to emphasize the hierarchy of pages, now that the namespace is browsable. 

> but this is really something I have no experience with whatsoever,

@kenranunderscore yes but are you interested in gaining said experience? ;)
