### ISSUE TITLE
Open issues wrt `nix` infrastructure

### ISSUE THREAD

**Issue by MangoIV** [flora-pm/flora-server#379]
### important
- [ ] support additional systems
  - [ ] `x86_64-darwin`, `aarch64-darwin`
  - [ ] `aarch64-linux` 
- [ ] provide `app`s that provision a testing environment (databases, see `flora` `checkPhase`)
- [ ] seperate out tests and test frontend 

### nice to have 
- [ ] build containers with nix (probably hard, probably  needs cross compilation) 
- [ ] use [`flake-parts`](https://flake.parts)
- [ ] automatically update the `flake.lock`

### needs discussion with maintainer
- [ ] deploy with nix

**Comment by tchoutri** [comment]
This ticket is more than one year old, at this point I think it's better to open new ones that will be more active.
