### ISSUE TITLE
Installation section gives misadvice about version (at least for 0.x.y.z)

### ISSUE THREAD

**Issue by dpwiz** [flora-pm/flora-server#434]
It says `In your cabal file: acme-example ^>= 0.1`. But it doesn't know the actual version policy for the package.

Of course, there's PVP with MAJOR.MAJOR.MINOR.PATCH scheme. But even if we ignore all the explicit non-practitioners there's something like a custom for "experimental", where the "epoch" major being `0`, shifts the breaking part further to the right.

Ideally the packages should signal their "breaking" scheme somewhere in the package description, but that's outside the Flora powers (`x-breaking: 0.x.y`, anyone?).

I think at least a hack for `0.x` would make the advice a bit more resilient by recommending `acme-example ^>= 0.1.2` instead.

**Comment by tchoutri** [comment]
@dpwiz Ok I can understand the argument for the 0.x version series. Can I let you submit a patch? This is the bit of code you want to modify: https://github.com/flora-pm/flora-server/blob/bc2a869846b1c1caf1320af827faa15b9f395aba/src/web/FloraWeb/Pages/Templates/Packages.hs#L298-L310

**Comment by tchoutri** [comment]
@dpwiz Do you still wish to tackle that one or can I reassign it?

**Comment by tchoutri** [comment]
closed by #490
