### ISSUE TITLE
"Tested Compilers" summary incomplete on `safe-json` package

### ISSUE THREAD

**Issue by Vlix** [flora-pm/flora-server#449]
## Expected Behaviour

Show all the GHC versions the package is tested with.

## Actual Behaviour

Only show 2 of the 5 versions

## Instructions for reproduction

Go to https://flora.pm/packages/@hackage/safe-json/1.2.0.0 and see only `8.10.7` and `9.0.2` on the right side of the page.
Compare with https://hackage.haskell.org/package/safe-json-1.2.0.0/safe-json.cabal where it says:

```
tested-with:
    GHC == 8.10.7 , GHC == 9.0.2 , GHC == 9.2.8 , GHC == 9.4.5 , GHC == 9.6.2
```

**Comment by tchoutri** [comment]
Quite surprising indeed, I reindexed Hackage with an updated list today: https://github.com/flora-pm/flora-server/blob/main/src/core/Flora/Import/Package.hs#L124-L171

**Comment by tchoutri** [comment]
Reindexing did the job. Closing.

**Comment by alaendle** [comment]
@tchoutri - not a big issue, but it seems to still be a problem - e.g. see https://flora.pm/packages/@hackage/wled-json
