### ISSUE TITLE
Cooperation suggession with HackageUI

### ISSUE THREAD

**Issue by visortelle** [flora-pm/flora-server#60]
Hello! I recently started this project: https://github.com/visortelle/hackage-ui/
Today I got a thought here. Maybe it would make sense to cooperate somehow?

I see it as you concentrate on APIs, I'm continuing work on UI.
HackageUI potentially can consume both APIs - Hackage and Flora.

I don't think that `aria-*` accessibility and dark mode are necessary from the start, but all this stuff can be added later.

Please try it here https://hackage-ui.vercel.app/ and let me know what you think. 😉

**Comment by tchoutri** [comment]
Hi @visortelle, you could absolutely plug yourself onto the APIs Flora would expose but I'd rather work on a server-side rendered Web UI with very little client scripts. :)

**Comment by visortelle** [comment]
OK. 

I'll add Flora integration after it will be ready to use.
Closing for now. 🙂
