### ISSUE TITLE
URL uniformisation for namespaces prefix (/@ vs /&40)

### ISSUE THREAD

**Issue by TixieSalander** [flora-pm/flora-server#601]
## Environment

* Operating System: Tested on the latest stable web browsers (Firefox, Chromium & Safari) on macOS
* Version or commit: Tested on the deployed version at https://flora.pm

## Expected Behaviour

All URLs containing a namespace will display the `@` character correctly

## Actual Behaviour

While a package main pages and handling it correctly (for example https://flora.pm/packages/@hackage/diagrams-pgf and https://flora.pm/packages/@hackage), all the links from those pages to other sub-pages or other related pages have URLs where `@` is replaced by `%40`:
- Specific version: https://flora.pm/packages/%40hackage/diagrams-pgf/1.4.2
- Dependencies: https://flora.pm/packages/%40hackage/diagrams-pgf/1.4.2.1/dependencies
- Namespace index (link of the breadcrumb/header): https://flora.pm/packages/%40hackage?page=1

It would be best to have one single behavior (even if both URLs manually entered either with `@` or `%40` displays the expected pages).

With that last point comes an additional issues: several URLs are displaying the same content. Duplicated content is not a desired behavior since it gonna have a negative impact on search engines and other tools who try to make sense of the website's structure.

To avoid duplicate content either, we can add:
1. A redirection (for every `/%40foobar` URLs to be redirected to `/@foobar` 
2. A [canonical link tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#canonical) in the <head> of both version pointing to the preferred version (as declared my preference come to the version with `@`.

**Comment by tchoutri** [comment]
Closed by #765
