### ISSUE TITLE
Unreadable text on dependency pages and cards (light theme)

### ISSUE THREAD

**Issue by dpwiz** [flora-pm/flora-server#83]
I think it is due `.text-slate-300` and `.text-grey-200` classes used with inappropriate background.

https://dev.flora.pm/packages/@haskell/Cabal/dependencies

![Capture d’écran de 2022-04-15 13-22-20](https://user-images.githubusercontent.com/486682/163560050-fb742529-f8a6-4d0e-ab79-2900334f91dc.png)

https://dev.flora.pm/categories

![Capture d’écran de 2022-04-15 13-25-41](https://user-images.githubusercontent.com/486682/163560546-cb488166-799b-4ec0-ba80-692d8b9840d6.png)

**Comment by gbogard** [comment]
I think this should be closed in favour of #84. I've started working on fixing these issues :)
