### ISSUE TITLE
Package page UI alignment

### ISSUE THREAD

**Issue by tchoutri** [flora-pm/flora-server#91]
In the package page, two things are noticed:

1. The right column is not justified to the right anymore, and the wrapping of the dependents is not applied anymore
2. Alpine has trouble rendering some stuff, which inserts `undefined` in the page

![Screenshot 2022-04-26 at 15-45-34 Flora Package](https://user-images.githubusercontent.com/15848443/165314418-de057fbc-9c66-4212-b682-dc9533476df0.png)

![Screenshot_20220426_154624](https://user-images.githubusercontent.com/15848443/165314798-dbf5fe7e-af00-4f4c-960c-654997554286.png)

The issue can be reproduced at https://dev.flora.pm/packages/@haskell/bytestring

**Comment by gbogard** [comment]
On it!
